// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using UpGoDown.Api.Data;

#nullable disable

namespace UpGoDown.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250610120000_InitialCreate")]
partial class InitialCreate
{
}
