// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using UpGoDown.Api.Data;

#nullable disable

namespace UpGoDown.Api.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

        modelBuilder.Entity("UpGoDown.Api.Data.AppUser", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Login").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Role").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasDefaultValue("Student");
                b.HasKey("Id");
                b.HasIndex("Login").IsUnique();
                b.ToTable("Users");
            });

        modelBuilder.Entity("UpGoDown.Api.Data.LevelAttempt", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("LevelId").HasColumnType("integer");
                b.Property<string>("PointsHistoryJson").IsRequired().HasColumnType("text");
                b.Property<string>("SceneJson").IsRequired().HasColumnType("text");
                b.Property<int>("StepsCount").HasColumnType("integer");
                b.Property<bool>("Success").HasColumnType("boolean");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("UserId", "LevelId", "CreatedAt");
                b.ToTable("LevelAttempts");
            });

        modelBuilder.Entity("UpGoDown.Api.Data.LevelAttempt", b =>
            {
                b.HasOne("UpGoDown.Api.Data.AppUser", "User")
                    .WithMany("Attempts")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

        modelBuilder.Entity("UpGoDown.Api.Data.AppUser", b =>
            {
                b.Navigation("Attempts");
            });
#pragma warning restore 612, 618
    }
}
